name: Hotbar
main: ARTulloss\Hotbar\Main
api: 3.0.0
version: 2.0.2
author: ARTulloss
website: github.com/artulloss
description: Hotbar Items!
loadbefore: [FloatingHotbar]

permissions:
  hotbar.view:
    default: op
    description: Allows a user to run the hotbar command to view a list of all registered hotbars and the worlds they are assigned to